### ISSUE TITLE
compatibility issue with immersive weathering | 1.19 fabric

### ISSUE THREAD

**Issue by Surpos0** [CleverNucleus/RelicEx#13]
Game is saying that im on wrong version of cloth config, but when i delete RelicEx, game starts as normal. With no changes of cloth config.

**Comment by CleverNucleus** [comment]
Hi there,
Please provide the versions of the mods you are using as well as the error message.
Thanks.

**Comment by Surpos0** [comment]
relicex-3.2.3
cloth-config-8.0.75-fabric
immersive_weathering-1.0.1-1.19

fabric loader log:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Immersive Weathering' (immersive_weathering) 1.0.1-1.19_SNAPSHOT with any version that is compatible with:
		 - cloth-config 8.0.75
Unmet dependency listing:
	 - Mod 'Immersive Weathering' (immersive_weathering) 1.0.1-1.19_SNAPSHOT requires any 7.x version of mod 'Cloth Config v8' (cloth-config), which can't be loaded due to other constraints!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:29)
	at crystallauncher.MineClient.start(MineClient.java:213)
	at crystallauncher.MineClient.main(MineClient.java:36)

**Comment by CleverNucleus** [comment]
Hi there,
It seems Immersive Weathering has not updated there [dependency for Cloth Config](https://github.com/AstralOrdana/Immersive-Weathering/blob/d391635b77659503f180f44605d5994860e8a688/src/main/resources/fabric.mod.json#L41) to use v8.x. RelicEx requires any version of Cloth Config v8 or greater, whereas Immersive Weathering requires any v7.x version of Cloth Config. 

In all likelihood, Immersive Weathering will work on the later version of Cloth Config, just as RelicEx will probably work with the earlier version of Cloth Config. I advise you to either:

 - Request that the developer(s) of Immersive Weathering update their dependency on Cloth Config to 8.x, or
 - Edit the fabric.mod.json contained in either the RelicEx or Immersive Weathering jar to depend on the same version of Cloth Config.

Thanks.
