### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by Entchenbrot** [CleverNucleus/RelicEx#35]
I added RelicEx to my mods (Fabric, 1.18.2) and sometimes I get this crash:

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_1309.handler$hhc000$relicex_dropLoot(class_1309.java:58354)
	at net.minecraft.class_1309.method_16077(class_1309.java:1404)
	at net.minecraft.class_1308.method_16077(class_1308.java:507)
	at net.minecraft.class_1309.method_16080(class_1309.java:1374)
	at net.minecraft.class_1309.method_6078(class_1309.java:1329)
	at net.minecraft.class_1308.method_6078(class_1308.java:9304)
	at net.minecraft.class_1309.method_5643(class_1309.java:1182)
	at net.minecraft.class_1308.method_6121(class_1308.java:1419)
	at net.minecraft.class_1366.method_6288(class_1366.java:152)
	at net.minecraft.class_1366.method_6268(class_1366.java:144)
	at net.minecraft.class_4135.method_6268(class_4135.java:65)
	at net.minecraft.class_1355.method_38849(class_1355.java:119)
	at net.minecraft.class_1308.method_6023(class_1308.java:750)
	at net.minecraft.class_1309.method_6007(class_1309.java:2609)
	at net.minecraft.class_1308.method_6007(class_1308.java:546)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_1560.method_6007(class_1560.java:257)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: minecraft:enderman (net.minecraft.class_1560)
	Entity ID: 741
	Entity Name: Enderman
	Entity's Exact location: 3724.65, 88.00, 5337.69
	Entity's Block location: World: (3724,88,5337), Section: (at 12,8,9 in 232,5,333; chunk contains blocks 3712,0,5328 to 3727,255,5343), Region: (7,10; contains chunks 224,320 to 255,351, blocks 3584,0,5120 to 4095,255,5631)
	Entity's Momentum: -0.19, -0.08, 0.05
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['entchenbrot'/443, l='ServerWorld minecraft:the_end New World', x=3791.63, y=99.25, z=5335.88]]
	Chunk stats: 4491
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (-110,76,-538), Section: (at 2,12,6 in -7,4,-34; chunk contains blocks -112,0,-544 to -97,255,-529), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 64617574 game time, 62939050 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 8275 (now: true), thunder time: 11383 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)
	
Normally I can fix it with just deleting the file containing the entities for that region but maybe there is another way to fix it :/ I could imagine that the problem might be Eldritch Mobs since this mod adds changes to the loot table of some mobs but I'm not sure about it. The problem occurs every ~300-500 blocks when rendering new chunks, this would be fitting to the spawn weight of these adapted mobs from Eldritch Mobs but I really don't know

Thanks in advance!

**Comment by CleverNucleus** [comment]
Hi there,
Could I get the entire crash log please? Could definitely be an incompatibility with Eldritch Mobs that would then need fixing but could also be something less serious.
Thanks.

**Comment by Entchenbrot** [comment]
Yes, of course! (I uploaded it as .txt file for better overview)
I tried removing Eldritch Mobs but that didn't fix the problem (at least not for the world I'm playing in, I don't know how it would be in a new world generated without this mod)
Removing RelicEx worked, after that no new crashes happened

[crash-2023-02-05_17.59.55-server.txt](https://github.com/CleverNucleus/RelicEx/files/10611935/crash-2023-02-05_17.59.55-server.txt)

**Comment by CleverNucleus** [comment]
Ah okay,
I think this may have been an issue I've already fixed. Your issue should be fixed if you use the latest release RelicEx and its dependencies, namely:
- Data Attributes v1.3.2
- PlayerEx v3.4.2
- RelicEx v3.1.6

Let me know.
Thanks.

**Comment by Entchenbrot** [comment]
Thanks for your help!
Unfortunately I can't test it since some of the mods I'm using require an older version of Fabric API than the latest RelicEx version :/ But still thank you very much

**Comment by CleverNucleus** [comment]
Hi there,
I've done some testing and indeed I think the latest release does not have this problem - therefore, I'll close this issue now.
Thanks.
